EMOJI_MAP = {
    # --- Smileys & Emotions ---
    ':smile:': '😊',
    ':happy:': '😀',
    ':grinning:': '😁',
    ':lol:': '😂',
    ':rofl:': '🤣',
    ':laughing:': '😆',
    ':wink:': '😉',
    ':blush:': '☺️',
    ':star_struck:': '🤩',
    ':cool:': '😎',
    ':smirk:': '😏',
    ':relieved:': '😌',
    ':yum:': '😋',
    ':thinking:': '🤔',
    ':shy:': '🫣',
    ':shy1:': '🤭',
    ':sleepy:': '😴',
    ':drool:': '🤤',
    ':neutral:': '😐',
    ':expressionless:': '😑',
    ':unamused:': '😒',
    ':sad:': '😔',
    ':cry:': '😢',
    ':crying:': '😭',
    ':sob:': '😭',
    ':fear:': '😨',
    ':angry:': '😠',
    ':rage:': '😡',
    ':mind_blown:': '🤯',
    ':clown:': '🤡',
    ':poop:': '💩',
    ':ghost:': '👻',
    ':skull:': '💀',
    ':sweat_smile:': '😅',
    ':hot:': '🥵',
    ':cold:': '🥶',
    ':woozy:': '🥴',
    ':nauseated:': '🤢',
    ':vomit:': '🤮',
    ':sneezing:': '🤧',

    # --- Love & Hearts ---
    ':heart:': '❤️',
    ':red_heart:': '❤️',
    ':orange_heart:': '🧡',
    ':yellow_heart:': '💛',
    ':green_heart:': '💚',
    ':blue_heart:': '💙',
    ':purple_heart:': '💜',
    ':brown_heart:': '🤎',
    ':black_heart:': '🖤',
    ':white_heart:': '🤍',
    ':sparkling_heart:': '💖',
    ':two_hearts:': '💕',
    ':revolving_hearts:': '💞',
    ':heartbeat:': '💓',
    ':growing_heart:': '💗',
    ':heartpulse:': '💗',
    ':heart_decoration:': '💟',
    ':cupid:': '💘',
    ':love_letter:': '💌',
    ':kiss:': '😘',
    ':kiss-mark:': '💋',
    ':couple_with_heart:': '💑',
    ':hug:': '🤗',
    ':ring:': '💍',
    ':couple:': '👩‍❤️‍👨',
    ':wedding:': '👰',

    # --- Hand Gestures & Reactions ---
    ':thumbsup:': '👍',
    ':thumbsdown:': '👎',
    ':clap:': '👏',
    ':ok_hand:': '👌',
    ':pray:': '🙏',
    ':wave:': '👋',
    ':fist:': '✊',
    ':muscle:': '💪',
    ':peace:': '✌️',
    ':callme:': '🤙',
    ':point_up:': '☝️',
    ':point_down:': '👇',
    ':point_left:': '👈',
    ':point_right:': '👉',
    ':middle_finger:': '🖕',

    # --- Party & Fun ---
    ':tada:': '🎉',
    ':party:': '🥳',
    ':fire:': '🔥',
    ':100:': '💯',
    ':eyes:': '👀',
    ':shrug:': '🤷',
    ':rocket:': '🚀',
    ':star:': '⭐',
    ':boom:': '💥',
    ':sparkles:': '✨',
    ':zzz:': '💤',
    ':crown:': '👑',

    # --- Adult Chat Symbols / Suggestive Emojis ---
    ':eggplant:': '🍆',
    ':peach:': '🍑',
    ':sweat_drops:': '💦',
    ':tongue:': '👅',
    ':lips:': '👄',
    ':cherries:': '🍒',
    ':banana:': '🍌',
    ':carrot:': '🥕',
    ':bed:': '🛏️',
    ':smoking:': '🚬',
    ':beer:': '🍺',
    ':wine:': '🍷',
    ':cocktail:': '🍸',
    ':champagne:': '🍾',
    ':pill:': '💊',
    ':syringe:': '💉',
}
